fix: tpep and tpl impl for thirdparty rework
supertokens/supertokens-web-js pull request #74
Opened 2022-11-29 10:43 UTC by sattvikc

## Summary of change

(A few sentences about this PR)

## Related issues

-   Link to issue1 here
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `lib/ts/version.ts`
-   [ ] `webJsInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2022-11-30 05:27 UTC, rishabhpoddar requested changes

2022-11-30 05:27 UTC, rishabhpoddar commented on lib/ts/recipe/thirdpartyemailpassword/index.ts
missed getConfiguredThirPartyProviders?

2022-11-30 05:27 UTC, rishabhpoddar commented on lib/ts/recipe/thirdpartypasswordless/index.ts
> +        userContext: any;
missed getConfiguredThirPartyProviders?

2023-01-06 05:00 UTC, sattvikc commented on lib/ts/recipe/thirdpartyemailpassword/index.ts
This function is removed

2023-01-06 08:28 UTC, rishabhpoddar requested changes

2023-01-06 08:28 UTC, rishabhpoddar commented on lib/ts/recipe/multitenancy/index.ts
> +    static getLoginMethods(input: { tenantId?: string; options?: RecipeFunctionOptions; userContext: any }): Promise<{
- userContext should be optional
- Since nothing in the input object is compulsory, the whole input object should be optional too

2023-01-06 08:28 UTC, rishabhpoddar commented on lib/ts/recipe/multitenancy/recipe.ts
> +    static RECIPE_ID = "thirdparty";
wrong recipe ID..

2023-01-06 08:28 UTC, rishabhpoddar commented on lib/ts/recipe/multitenancy/recipe.ts
> +            let error = "No instance of ThirdParty found. Make sure to call the ThirdParty.init method.";
wrong message

2023-01-06 08:28 UTC, rishabhpoddar commented on lib/ts/recipe/multitenancy/recipe.ts
> +    static reset(): void {
call this reset function in the tests - where other recipe's reset functions are being called

2023-01-06 08:28 UTC, rishabhpoddar commented on lib/ts/recipe/multitenancy/recipeImplementation.ts
> +        clientType?: string;
you are taking clientType as an input here but reading it from st.clientType

2023-01-07 07:51 UTC, rishabhpoddar requested changes

2023-01-10 06:52 UTC, rishabhpoddar requested changes

2023-01-10 06:52 UTC, rishabhpoddar commented on test/with-typescript/index.ts
>          functions: getThirdPartyPasswordlessFunctions,
make changes

2023-01-11 05:46 UTC, rishabhpoddar approved these changes

2023-01-11 05:46 UTC, rishabhpoddar commented
Size check and changelog PR checks are failing @sattvikc

2023-01-11 08:00 UTC, merged