feat: re-export getglobalclaimsvalidators from website
supertokens/supertokens-web-js pull request #85
Opened 2023-03-02 05:40 UTC by alisher-aituarov

## Summary of change

Re-exports getglobalclaimsvalidators function from website

## Related issues

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [x] Changelog has been updated
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `lib/ts/version.ts`
-   [ ] `webJsInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [x] Had run `npm run build-pretty`
-   [x] Had installed and ran the pre-commit hook
-   [x] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2023-03-07 08:56 UTC, porcellus requested changes

2023-03-13 08:46 UTC, porcellus approved these changes

2023-03-13 09:58 UTC, rishabhpoddar commented
- size check in PR
- update the dependency version on supertokens-website

2023-03-14 09:07 UTC, rishabhpoddar approved these changes

2023-03-14 09:08 UTC, rishabhpoddar approved these changes

2023-03-14 09:08 UTC, rishabhpoddar commented on package.json
> +        "supertokens-website": "^17.0.0"
```suggestion
        "supertokens-website": "^16.0.3"
```

2023-03-14 09:09 UTC, merged